[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "S", "B", "UP"]
ignore = ["S104"]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = ["S101"]

[tool.pytest.ini_options]
testpaths = ["tests"]
